version: "2"
services:
  test1:
    image: php:5.6-apache
    ports:
      - 8081:80
    restart: always

  test2:
    image: php:5.6-apache
    ports:
      - 8082:80
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --appendonly yes

  redmon:
    image: vieux/redmon
    links:
      - redis:redis
    ports:
      - 4567:4567
    command: -r redis://redis:6379

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160
      - 4161:4161
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - 32784:4171

  postgres-gui:
    build: ./pgweb/
    ports:
      - 8532:8080
    links:
      - postgres:postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5431:5432
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d

  # arangodb:
  #   image: arangodb/arangodb
  #   restart: always  
  #   environment: 
  #     - ARANGO_RANDOM_ROOT_PASSWORD=1
  #   ports: 
  #     - 8529:8529

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8481:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
