version: "2"
services:
  # test1:
  #   image: php:5.6-apache
  #   ports:
  #     - 8081:80
  #   restart: always

  # test2:
  #   image: php:5.6-apache
  #   ports:
  #     - 8082:80
  #   restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --appendonly yes

  redmon:
    image: vieux/redmon
    links:
      - redis:redis
    ports:
      - 4567:4567
    command: -r redis://redis:6379

  postgres-gui:
    build: ./pgweb/
    ports:
      - 8087:8080
    links:
      - postgres:postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5431:5432
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d

  reverse-proxy:
    image: traefik
    command: --configFile=traefik.toml
    ports:
      - "80:80"
      - "8562:8080"
    volumes:
      - ./rapis_router/traefik.toml:/etc/traefik/traefik.toml

  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380
