
traefikLogsFile = "/var/log/traefik/traefik.log"
accessLogsFile = "/var/log/traefik/access.log"
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[traefikLog]
  filePath = "/var/traefik/traefik.log"
  format = "json"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[etcd]
  endpoint = "etcd:2379"
  watch = true
  prefix = "/traefik"
  
[api]
  entryPoint = "traefik"
  dashboard = true # WebUIの有効化
