defaultEntryPoints = ["http", "https"]

[traefikLog]
  filePath = "/var/traefik/traefik.log"
  format = "json"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "YOUR EMAIL"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0
  [[acme.domains]]
    main = "*.shikugawa.net"

[file]
watch = true

[backends]
  [backends.jenkins]
    [backends.jenkins.servers]
      [backends.jenkins.servers.server0]
        url = "http://jenkins:8080" 
        weight = 1

[frontends]
  [frontends.jenkins]
    backend = "jenkins"
    passHostHeader = true # これをつけないとヘッダ情報がサービス側に飛ばない

    [frontends.jenkins.routes.host]
      rule = "Host:jenkins.shikugawa.net"

[api]
  entryPoint = "traefik"
  dashboard = true # WebUIの有効化
